### ISSUE TITLE
Search Result is unreadable

### ISSUE THREAD

**Issue by CarlosPet** [fengtan/ldap-explorer#52]
![Screenshot 2023-09-29 at 12 19 46](https://github.com/fengtan/ldap-explorer/assets/143050490/15afdea8-03f3-48ef-9344-95869c363a4b)

When the search function is used, the resulting windows is presented in this vertical format instead of the readable one that gets displayed when exploring the tree manually.

**Comment by fengtan** [comment]
I often run into this issue myself too. Up until now I have been using the field `Attributes` to reduce the number of columns and make results easier to read:

![Screenshot from 2023-10-01 22-58-28](https://github.com/fengtan/ldap-explorer/assets/1483301/c0bc5702-bb4b-41ac-bbae-99cbcbaf629c)

That being said that is certainly not ideal.

@CarlosPet I have just published a pre-release [1.2.3-rc](https://github.com/fengtan/ldap-explorer/releases/tag/1.2.3-rc) with a CSS update that should make columns are least `6em` wide. Do you think you could try it and let me know if things look better? You can download the `.vsix` archive from the pre-release page and install it locally like so: ![install_vsix](https://user-images.githubusercontent.com/1483301/202880388-7a264240-76a3-49f7-9552-145573437a67.png)

**Comment by CarlosPet** [comment]
Hey, thanks a lot for the quick response. It does improve readability a bit and at least allowed me to finish what i was working on. Is there any way to change orientation of the displayed data to be two columns and several rows with the attributes? like it is shown when manually exploring the three instead of searching. those are perfectly fine to read

**Comment by fengtan** [comment]
Thanks for testing! I have just released [1.2.3](https://github.com/fengtan/ldap-explorer/releases/tag/1.2.3) and published it to VS Code Marketplace.

> Is there any way to change orientation of the displayed data to be two columns and several rows with the attributes? like it is shown when manually exploring the three instead of searching.

I am afraid there is no way to do that. When submitting a search query, you may end up with multiple results (multiple LDAP entries) and each of them may have multiple attributes. Having one _row_ for every search result makes the list scrollable, plus headers are sticky (that would not be case if we had one _column_ for every search result). This is different from the view you get when exploring the tree, which always shows only one LDAP entry at a time and thus works well with 2 columns (one for attribute names, one for attribute values).
