### ISSUE TITLE
Connection status icon with RED and GREEN

### ISSUE THREAD

**Issue by tpfarul** [fengtan/ldap-explorer#53]
I would like to know, if the LDAP server connection connected and ACTIVE or NOT much easy way to understand. I prefer to show with GREEN or RED icon status. so that I can disconnect when I don't need it.

**Comment by fengtan** [comment]
So, currently, you can tell which connection is active by checking whether the circle is filled or not (you can think of it like a light bulb):

![active_connection](https://github.com/fengtan/ldap-explorer/assets/1483301/4a1df87d-d126-4343-964f-1ed6a3694c32)

While I see the convenience or turning this into green/red icons, there are no such icons in the [VS Code icon library](https://microsoft.github.io/vscode-codicons/dist/codicon.html) which means we would have to find those icons somewhere else and possibly bring in a third-party library.

We would also have to account for accessibility as colorblind people may have a hard time making a distinction between red and green icons.
