### ISSUE TITLE
Display search result as List instead of columns

### ISSUE THREAD

**Issue by tpfarul** [fengtan/ldap-explorer#54]
When I access CN or DN data then it shows as List which is easily readable. but when I search with attribute and it's results are shown in column format which is always wrapped. This results very hard to read it. I prefer to show as list like [overview.png](https://github.com/fengtan/ldap-explorer/blob/master/screenshots/overview.png) screenshot.

**Comment by fengtan** [comment]
That bothers me as well, but changing the orientation of search results is not an option as you may end up with multiple LDAP results (see [this thread](https://github.com/fengtan/ldap-explorer/issues/52#issuecomment-1747923891) for more details).

Alternatively we could add a hyperlink to each search result so people would be able to display a single search entry from the results as a List. I tried to implement that but ran into https://github.com/microsoft/vscode-webview-ui-toolkit/issues/484. We would have to wait for this upstream issue to be resolved first.
