### ISSUE TITLE
Search results to export in CSV or EXCEL format

### ISSUE THREAD

**Issue by tpfarul** [fengtan/ldap-explorer#55]
Please add export support to CSV or EXCEL format.

**Comment by fengtan** [comment]
That is a good idea, thanks for bringing this up @tpfarul !

I have just published a pre-release [1.3.0-rc](https://github.com/fengtan/ldap-explorer/releases/tag/1.3.0-rc) with support for CSV exports. When listing LDAP entries (either via search results or by opening a single entry from the tree view) there should be a new button `Export CSV` at the bottom of the page: 

![csv_button](https://github.com/fengtan/ldap-explorer/assets/1483301/d98d95e2-6c5f-4426-97b2-e3ef914eb74b)

Do you mind trying it? You can download the the `.vsix` archive from the pre-release page and install it locally like this:

![install_vsix](https://user-images.githubusercontent.com/1483301/202880388-7a264240-76a3-49f7-9552-145573437a67.png)

If that works for you then I will make a full release and publish to Marketplace.

**Comment by fengtan** [comment]
Released [1.3.0](https://github.com/fengtan/ldap-explorer/releases/tag/1.3.0) and published to VS Code Marketplace.
